apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simulacao-consumo-hpa
  labels:
    app: simulador-consumo
  namespace: teste-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simulacao-consumo-deployment
  minReplicas: 1
  maxReplicas: 20
  # quanto atingi 50% de utilização da cpu com 
  # base na configuração do request (no caso # 1000m = 1 core)
  # vai acionar nova replica, abaixo disso, retira nova replica
  # respeitando mínimo de replica e máximo
  targetCPUUtilizationPercentage: 50 
                                    