apiVersion: v1
kind: Service
metadata:
  name: api-agenda-deployment
  labels:
    app: simulador-consumo
  namespace: teste-hpa
spec:
  selector:
    app: simulador-consumo
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer