apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-api-agenda-deployment
  labels:
    app: api-agenda
  namespace: agenda
spec:
  selector:
    matchLabels:
      app: db-api-agenda
  template:
    metadata:
      labels:
        app: db-api-agenda
    spec:
      containers:
        - name: db-api-agenda
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          envFrom:
            - secretRef:
                name: secret-db-api-agenda
          resources:
            requests:
              memory: 800Mi
              cpu: 3m
            limits:
              memory: 3000Mi
              cpu: 1000m