apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scw-pvc-sqlserver-db
  namespace: agenda 
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: scw-bssd-retain
