apiVersion: apps/v1
kind: Deployment
metadata:
  name: depliyment-app-nxing
  namespace: space-blue
spec:
  selector:
    matchLabels:
      app: app-nxing
  template:
    metadata:
      labels:
        app: app-nxing
    spec:
      containers:
      - name: app-nxing
        image: kubedevio/nginx-color:blue