apiVersion: apps/v1
kind: Deployment
metadata:
  name: depliyment-app-nginx
  namespace: space-green
spec:
  selector:
    matchLabels:
      app: app-nginx
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
      - name: app-nginx
        image: kubedevio/nginx-color:green