apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server-deployment
  labels:
    app: api-agenda
spec:
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - name: ql-server
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          value: "Pass@word"
        - name: ACCEPT_EULA
          value: "Y"
