apiVersion: v1
kind: Service
metadata:
  name: sql-server-service
  labels:
    app: api-agenda
spec:
  selector:
    app: sql-server
  ports:
    - port: 1433
      targetPort: 1433
      name: tcp
  type: ClusterIP