apiVersion: networking.k8s.io/v1 
kind: NetworkPolicy
metadata:
  name: nginx-network-police
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
    - Ingress #política de entrada
    - Egress  #política de saída
  ingress:
    - from:
      # - ipBlock:
      #     cidr: 172.17.0.0/16
      #     except:
      #       - "172.17.10.223"
      - podSelector:
          matchLabels:
            app: ubuntu
        namespaceSelector:
          matchLabels:
            ns: nginx
      ports:
        - port: 80
          protocol: TCP
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: ubuntu
        namespaceSelector:
          matchLabels:
            ns: nginx
      ports:
        - port: 80
          protocol: TCP