apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-agenda-deployment
  labels:
    app: api-agenda
  namespace: agenda
spec:
  selector:
    matchLabels:
      app: api-agenda
  template:
    metadata:
      labels:
        app: api-agenda
    spec:
      containers:
        - name: api-agenda
          image: marcioalmeidarosa/api_agenda:latest
          ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: secret-api-agenda
          resources:
            requests:
              memory: "10Mi"   # 10MB
              cpu: "100m"      # 1000m = 1 core de cpu | 100m = 10% de 1 core de cpu
            limits:
              memory: "100Mi"  # 100MB
              cpu: "500m"      # 1000m = 1 core de cpu | 100m = 50% de 1 core de cpu