apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-agenda-deployment
  labels:
    app: api-agenda
  namespace: agenda
spec:
  selector:
    matchLabels:
      app: api-agenda
  template:
    metadata:
      labels:
        app: api-agenda
    spec:
      containers:
        - name: api-agenda
          image: marcioalmeidarosa/api_agenda:latest
          ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: secret-api-agenda
          env:
            - name: MemoryCheckOptions__Threshold
              value: "184217728"
          resources:
            requests:
              memory: "200Mi"  # 10MB
              cpu: "500m"      # 1000m = 1 core de cpu | 100m = 10% de 1 core de cpu
            limits:
              memory: "200Mi"  # 100MB
              cpu: "500m"      # 1000m = 1 core de cpu | 100m = 50% de 1 core de cpu
          livenessProbe:
             httpGet:
               path: /health/live
               port: 80
               scheme: HTTP
             initialDelaySeconds: 3
             failureThreshold: 3
             successThreshold: 1
             periodSeconds: 10
             timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80
              scheme: HTTP
            initialDelaySeconds: 1
            failureThreshold: 2
            successThreshold: 1
            periodSeconds: 1
            timeoutSeconds: 1
          startupProbe:
            httpGet:
              path: /health/live
              port: 80
              scheme: HTTP
            initialDelaySeconds: 0
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 1
            timeoutSeconds: 2