apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-agenda
  labels:
    app: api-agenda
  namespace: agenda
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-agenda-deployment
  targetCPUUtilizationPercentage: 50