apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-agenda
  labels:
    app: api-agenda
  namespace: agenda
spec:
  minReplicas: 2
  maxReplicas: 6 #máquina de 4 cores (1core para banco, e 6 api consumindo 0,5 core cada uma)
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-agenda-deployment
  targetCPUUtilizationPercentage: 50