apiVersion: v1
kind: Service
metadata:
  name: api-agenda-service
  labels:
    app: api-agenda
  namespace: testando-health
spec:
  selector:
    app: api-agenda
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  type: LoadBalancer