apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template: 
    metadata:       
      labels:
        app: api
    spec:
      initContainers:
        - name: init-pod
          image: busybox:1.34.0
          command: ["sh", "-c", "until nslookup mongo-service.default.svc.cluester.local; do echo Aguardando banco de dados mongo...; sleep 2; done"]
      containers:
      - name: api
        image: fabricioveronez/pedelogo-catalogo:v1.0.0
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: api-configmap
        env:
          - name: Mongo__User
            valueFrom:
              secretKeyRef:
                key: MONGO_INITDB_ROOT_USERNAME
                name: mongodb-secret
          - name: Mongo__Password
            valueFrom:
              secretKeyRef:
                key: MONGO_INITDB_ROOT_PASSWORD
                name: mongodb-secret
        resources: {}