apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-conversao
  ports:
    - protocol: TCP
      port: 80 #vinculando com a porta do service
      targetPort: 8080 #vinculando com a porta do container
  type: ClusterIP #quando não declarado, ClusterIP é o tipo default