apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-deployment
spec:
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo-db
          image: mongo:5.0.3
          ports:
            - containerPort: 27017
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: mongouserroot
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: mongopwdrroot
            