apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-agenda-deployment
  labels:
    app: api-agenda
spec:
  selector:
    matchLabels:
      app: api-agenda
  template:
    metadata: 
      labels:
        app: api-agenda
    spec:
      containers:
        - name: api-agenda
          image: marcioalmeidarosa/api_agenda:latest
          ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: api-agenda-secret
            - configMapRef:
                name: database-sql-configmap
          env:
          - name: Ambiente
            valueFrom:
              configMapKeyRef:
                key: Ambiente
                name: database-sql-configmap