apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pedelogo-deployment
  labels:
    app: api-pedelogo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-pedelogo
  template:
    metadata:
      labels:
        app: api-pedelogo
    spec:
      containers:
        - name: api-pedelogo
          image: kubedevio/pedelogo-catalogo:v1.0.0
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "250m"
          envFrom:
            - configMapRef:
                name: configmap-mongodb-api-pedelogo
          env:
            - name: Mongo__User
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: secret-mongodb-api-pedelogo
            - name: Mongo__Password
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: secret-mongodb-api-pedelogo
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1 #definindo uma prioridade baixo, para que a outra regra tenha um peso maior
              podAffinityTerm:
                  topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - "mongodb-api-pedelogo"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 2 #definindo uma prioridade maior, para que tente ao máximo colocar as réplicas em outros nós
              podAffinityTerm:
                  topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - "api-pedelogo"