apiVersion: v1
kind: Service
metadata:
  name: api-pedelogo-service
  labels:
    app: api-pedelogo
spec:
  selector:
    app: api-pedelogo
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  type: LoadBalancer