apiVersion: batch/v1
kind: CronJob
metadata:
  name: roleta-cron-job
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace #encerra os jobs que ainda estão sendo executados e invadiram a janela do próximo job
                   # Forbid -> se ainda existir job sendo executados e der o tempo para o próximo job, ele não executa o próximo e ignora a sua vez.
  jobTemplate:
    metadata:
      name: roleta-job
    spec:
      backoffLimit: 10
      parallelism: 2
      completions: 3
      template:
        spec:
          containers:
          - name: job
            image: kubedevio/roleta
            args:
              - "-w"
              - "5"
              - "-c"
              - "2"
              - "-m"
              - "5"
          restartPolicy: Never      #não reestartar
                        #OnFailure  #somente quando falhar
                        #Always     #sempre que terminar a execução