apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-qos-best-effort
  labels:
    app: qos-best-effort
  namespace: teste-qos
spec:
  selector:
    matchLabels:
      app: qos-best-effort
  template:
    metadata:
      labels:
        app: qos-best-effort
    spec:
      containers:
        - name: qos-best-effort
          image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.4
          #resources:
          #  requests:
          #    memory: "10Mi"   # 10MB
          #    cpu: "100m"      # 1000m = 1 core de cpu | 100m = 10% de 1 core de cpu
          #  limits:
          #    memory: "100Mi"  # 100MB
          #    cpu: "500m"      # 1000m = 1 core de cpu | 100m = 50% de 1 core de cpu
          #command:
          #  - "/consumer"
          #  - "-port"
          #  - "8080"
          ports:
          - containerPort: 8080
