apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ291c2Vycm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: bW9uZ29wd2Rycm9vdA==