apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlserver-db-pv
  labels:
    type: sqlserver-db
  namespace: agenda
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /vol/mssql