apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-db-pvc
  namespace: agenda
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi #atribuir até o limite declarado no PersistentVolume
  storageClassName: manual