apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server-deployment
spec:
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - name: ql-server
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        envFrom:
          - configMapRef:
              name: database-sql-configmap
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKey:
              key: SA_PASSWORD
              name: database-sql-secret
        - name: ACCEPT_EULA
          valueFrom:
            configMapRefKey:
              key: ACCEPT_EULA
              name: database-sql-configmap