apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-agenda-deployment
  labels:
    app: api-agenda
  namespace: agenda
spec:
  selector:
    matchLabels:
      app: api-agenda
  template:
    metadata:
      labels:
        app: api-agenda
    spec:
      initContainers:
        - name: verificacao-db
          image: busybox:1.28
          command: ["sh", "-c", "until nslookup sqlserver-db-service.agenda.svc.cluster.local; do echo Aguardando banco de dados sql server...; sleep 2; done"]
        - name: inicializacao-container
          image: kubedevio/ubuntu-curl
          command:
            - "curl"
            - "-X"
            - "POST"
            - "http://pruu.herokuapp.com/dump/docker-agenda-init-containers"
      containers:
        - name: api-agenda
          image: marcioalmeidarosa/api_agenda:latest
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          env:
          - name: CONNECTION__CONNECTIONSTRINGS
            value: "Server=sqlserver-db-service.agenda.svc.cluster.local,1433;Database=DockerAgenda_Db;MultipleActiveResultSets=true;User ID=sa;Password=NovaSenhaParaSQLSErveR!"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "300Mi"
              cpu: "500m"
            limits:
              memory: "300Mi"
              cpu: "500m"
          startupProbe:
            httpGet:
              path: /health/live
              port: 80
              scheme: HTTP
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 5
            timeoutSeconds: 1
            initialDelaySeconds: 1
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80
              scheme: HTTP
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 3
            timeoutSeconds: 1
            initialDelaySeconds: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 3
            timeoutSeconds: 1
            initialDelaySeconds: 1
          lifecycle:
            postStart:
              exec:
                command:
                  - "curl"
                  - "-X"
                  - "POST"
                  - "http://pruu.herokuapp.com/dump/docker-agenda-life-cycle-start"
            preStop:
              exec:
                command:
                  - "curl"
                  - "-X"
                  - "POST"
                  - "http://pruu.herokuapp.com/dump/docker-agenda-life-cycle-stop"