apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-api-pedelogo-deployment
  labels:
    app: api-pedelogo
spec:
  selector:
    matchLabels:
      app: mongodb-api-pedelogo
  template:
    metadata:
      labels:
        app: mongodb-api-pedelogo
    spec:
      containers:
        - name: mongodb-api-pedelogo
          image: mongo:5.0.3
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: secret-mongodb-api-pedelogo
          resources:
            requests:
              cpu: "1000m"
              memory: "200Mi"
            limits:
              cpu: "1000m"
              memory: "200Mi"
          imagePullPolicy: Always