apiVersion: v1
kind: Service
metadata:
  name: api-pedelogo-catalogo-service-configmap
spec:
  selector:
    app: api-pedelogo-catalogo
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  type: LoadBalancer
