apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: testando-health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template: 
    metadata:       
      labels:
        app: api
    spec:      
      containers:
      - name: api
        image: kubedevio/pedelogo-catalogo:v1.0.0
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: api-configmap
        startupProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          failureThreshold: 5
          successThreshold: 1
          periodSeconds: 3
          initialDelaySeconds: 0
        readinessProbe:
          httpGet:
            path: /read
            port: 80
            scheme: HTTP
          failureThreshold: 2
          successThreshold: 1
          periodSeconds: 2
          initialDelaySeconds: 2
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          failureThreshold: 3
          successThreshold: 1
          periodSeconds: 5
          initialDelaySeconds: 3
        env:
          - name: Mongo__User
            valueFrom:
              secretKeyRef:
                key: MONGO_INITDB_ROOT_USERNAME
                name: mongodb-secret
          - name: Mongo__Password
            valueFrom:
              secretKeyRef:
                key: MONGO_INITDB_ROOT_PASSWORD
                name: mongodb-secret
