apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-state
spec:
  serviceName: nginx-state
  replicas: 1
  selector:
    matchLabels:
     app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: write-volume-page
          image: busybox
          command: ['sh', '-c', 'echo $(hostname) > /usr/share/nginx/html/index.html']
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: www
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: www
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: scw-bssd-retain
        resources:
          requests:
            storage: 1Gi