apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-conversao-cluster-ip
spec:
  selector:
    matchLabels:
      app: api-conversao-cluster-ip
  template:
    metadata:
      labels:
        app: api-conversao-cluster-ip
    spec:
      containers:
      - name: api-conversao-cluster-ip
        image: kubedevio/api-conversao:v1-machine-name